# Generated by Django 5.0.14 on 2026-07-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutabakatCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Bağlantı anahtarı')),
                ('dokuman_id', models.CharField(blank=True, max_length=50, verbose_name='Doküman ID')),
                ('cari_kod', models.CharField(blank=True, max_length=50, verbose_name='Cari kod')),
                ('cari_adi', models.CharField(blank=True, max_length=255, verbose_name='Cari adı')),
                ('karar', models.CharField(choices=[('mutabik', 'Mutabıkız'), ('itiraz', 'Mutabık Değiliz')], max_length=20, verbose_name='Karar')),
                ('mesaj', models.TextField(blank=True, max_length=255, verbose_name='Mesaj / açıklama')),
                ('ad_soyad', models.CharField(blank=True, max_length=150, verbose_name='Ad Soyad')),
                ('dosya', models.FileField(blank=True, upload_to='mutabakat_ekler/', verbose_name='Ek dosya')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Yanıt tarihi')),
            ],
            options={
                'verbose_name': 'Mutabakat cevabı',
                'verbose_name_plural': 'Mutabakat cevapları',
                'ordering': ['-olusturulma'],
            },
        ),
    ]
